name: Tests

on: [ push, pull_request ]

jobs:
  test:
    name: "PHP ${{ matrix.php }} - ${{ matrix.composer-dependency }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.0", "8.1", "8.2", "8.3" ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --prefer-stable

      - name: Execute tests
        run: vendor/bin/phpunit
